name: Run Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Ejecutar Pruebas Unitarias
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  

      - name: Instalar dependencias
        run: npm install
        working-directory: ./Portafolios/Flores_toribio

      - name: Ejecutar pruebas
        run: npm test
        working-directory: ./Portafolios/Flores_toribio
